language: ruby
script: 'true'
sudo: false

addons:
  postgresql: "9.4"

rvm:
  - 2.2.2

before_script:
  - bundle install --no-deployment
  - psql -c 'create database travis_ci_test;' -U postgres
  - CODECLIMATE_REPO_TOKEN=5ce1734b0cabfb053ca8870c3485b434214de9d970f17f5c407a6c11b5b1c00e bundle exec rake

test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres
