language: ruby
script: 'true'
sudo: false
git:
  depth: 1
addons:
  postgresql: '9.4'
rvm:
- 2.2.2
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres
addons:
  code_climate:
    repo_token: 291c5bd8afa95421a09175a285e6bbff1fdcd7148b0cbd55db679253fd142856
