language: ruby
script: 'true'
sudo: false

addons:
  postgresql: "9.4"
  code_climate:
    repo_token:
      secure: "XI/fO/0HpHAniwTZVUwJtZ4PmJZb0OPSDlYyaUk4m1RjSGfHGSmp3cy1aUcL4xVmyCBSYKmfiEBKBzMgAh/Rt7I9K/dbFD8/mY6lWbxKIHJpc9YT/4XoXEZndy+jN7eik8/oHgGzT2FAYSLZpCBrD/iAntUnmUK889LHXmJPvqE="

rvm:
  - 2.2.2

before_script:
  - bundle install --no-deployment
  - psql -c 'create database travis_ci_test;' -U postgres

test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres
