language: ruby
script: 'true'
sudo: false

addons:
  postgresql: "9.4"

rvm:
  - 2.2.2

before_script:
  - bundle install --no-deployment
  - psql -c 'create database travis_ci_test;' -U postgres

test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres
