development:
  adapter: postgresql
  encoding: unicode
  database: agenda_development
  pool: 5
  template: template0
  username: deployer
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: agenda_test
  pool: 5
  template: template0
  username: deployer
  password:


production:
  adapter: postgresql
  encoding: unicode
  database: agenda_production
  pool: 5
  template: template0
  username: deployer
  password:
