development:
  adapter: postgresql
  encoding: unicode
  database: agenda_development
  pool: 5
  template: template0
  username: postgres
  password: 13242

test:
  adapter: postgresql
  encoding: unicode
  database: agenda_test
  pool: 5
  template: template0
  username: postgres
  password: 13242


production:
  adapter: postgresql
  encoding: unicode
  database: agenda_production
  pool: 5
  template: template0
  username: postgres
  password: 13242
